#REWARD JASLP
jaspl:
  npcName: "Jaspl"
  item1:
    material: "DIAMOND_SWORD"
    itemDisplay: "une epée"
    enchant: "FIRE_ASPECT"
    level: "1"
    enchantDisplay: "Aura de Feu"
  item2:
    material: "DIAMOND_SWORD"
    itemDisplay : "une epée"
    enchant: "DAMAGE_ALL"
    level: "2"
    enchantDisplay: "Tranchant"

#REWARD VIKTOR
viktor:
  npcName: "Viktor"
  item:
    material: "DIAMOND_PICKAXE"
    itemDisplay: "une pioche"
    enchant: "LOOT_BONUS_BLOCKS"
    enchantDisplay: "Fortune"

#TRADE KEY
keyNamesOf :
  1: "§aT1"
  2: "§bT2"
  3: "§cT3"
noKeyFoundInInventory: "§fTu n'as pas de"
keyTraded: "§fTu as reçu 1 Clé §aQuête {keyBought} §fcontre {requiredKeyForTrade} Clé §aQuête {keySold}"

#Clé gagnées aléatoirement
# Quêtes journalière : 1% chance de gagner une clé T2 en plus d'une clé T1
# Quêtes hebdmadaire : 1% chance de gagner une clé T3 en plus d'une clé T2
random:
  randomNumber: "100"
  numberToReach:
    t1: "50"
    t2: "50"
  key:
    1: "T1"
    2: "T2"
    3: "T3"